# EProject-Phase-1/docker-compose.yml
version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # port cho ứng dụng backend (NodeJS, NestJS, v.v.)
      - "15672:15672"    # port cho web UI quản lý RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"    # Port mặc định cho MongoDB
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  api_gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "3003:3003"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
    restart: unless-stopped

  auth_service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "3000:3000"
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
      - mongodb
    restart: unless-stopped

  order_service:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order_service
    ports:
      - "3002:3002"
    volumes:
      - ./order:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
      - mongodb
    restart: unless-stopped

  product_service:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product_service
    ports:
      - "3001:3001"
    volumes:
      - ./product:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
      - mongodb
    restart: unless-stopped

volumes:
  rabbitmq_data:
  mongodb_data:
