version: "3.8"
services:
  mongo-auth:
    image: mongo
    container_name: mongo-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db

  mongo-product:
    image: mongo
    container_name: mongo-product
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

  mongo-order:
    image: mongo
    container_name: mongo-order
    ports:
      - "27019:27017"
    volumes:
      - mongo-order-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # giao diện web quản lý RabbitMQ

  auth:
    build: ./auth
    container_name: auth
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_AUTH_URI=mongodb://mongo-auth:27017/auth
      - JWT_SECRET=secret
    depends_on:
      - mongo-auth

  product:
    build: ./product
    container_name: product
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGODB_PRODUCT_URI=mongodb://mongo-product:27017/products
      - JWT_SECRET=secret
    depends_on:
      - mongo-product
      - rabbitmq

  order:
    build: ./order
    container_name: order
    restart: always
    ports:
      - "3002:3002"
    environment:
      - MONGODB_ORDER_URI=mongodb://mongo-order:27017/orders
      - JWT_SECRET=secret
    depends_on:
      - mongo-order
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order

volumes:
  mongo-auth-data:
  mongo-product-data:
  mongo-order-data:
