version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order
    networks:
      - backend

  auth:
    build: ./auth
    expose:
      - "3000"
    env_file:
      - ./auth/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend

  product:
    build: ./product
    expose:
      - "3001"
    env_file:
      - ./product/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend

  order:
    build: ./order
    expose:
      - "3002"
    env_file:
      - ./order/.env
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
